"""A compact RMPyL subset sufficient for the included RAO* experiments."""
from .constraints import ChanceConstraint, TemporalConstraint
from .defs import Choice, Event
from .episodes import Episode


def _as_episode(item):
    if isinstance(item, RMPyL):
        return item.plan
    return item


def sequence_composition(*episodes):
    return RMPyL().sequence(*episodes)


class RMPyL(object):
    def __init__(self, name="run()"):
        self.name = name
        self.plan = None
        self.user_defined_temporal_constraints = set()
        self.user_defined_chance_constraints = set()

    def __imul__(self, episode):
        self.plan = _as_episode(episode)
        return self

    @property
    def first_event(self):
        return self.plan.first_event if self.plan is not None else None

    @property
    def last_event(self):
        return self.plan.last_event if self.plan is not None else None

    @property
    def events(self):
        events = set()
        for ep in self._walk_episodes(self.plan):
            if isinstance(ep.start, Event):
                events.add(ep.start)
            if isinstance(ep.end, Event):
                events.add(ep.end)
        for tc in self.temporal_constraints:
            events.add(tc.start)
            events.add(tc.end)
        return list(events)

    @property
    def primitive_episodes(self):
        return [ep for ep in self._walk_episodes(self.plan) if ep.composition is None]

    @property
    def choices(self):
        return [ep.start for ep in self._walk_episodes(self.plan)
                if isinstance(ep.start, Choice)]

    @property
    def observations(self):
        return self.choices

    @property
    def temporal_constraints(self):
        constraints = set(self.user_defined_temporal_constraints)
        for ep in self._walk_episodes(self.plan):
            constraints.update(ep.temporal_constraints)
        return constraints

    def sequence(self, *episodes):
        eps = [_as_episode(ep) for ep in episodes if _as_episode(ep) is not None]
        seq = Episode.composite("sequence", eps)
        for left, right in zip(eps, eps[1:]):
            seq.temporal_constraints.add(
                TemporalConstraint(left.last_event, right.first_event,
                                   ctype="controllable", lb=0.0, ub=0.0)
            )
        return seq

    def parallel(self, *episodes):
        eps = [_as_episode(ep) for ep in episodes if _as_episode(ep) is not None]
        return Episode.composite("parallel", eps)

    def observe(self, choice_dict, *episodes):
        choice = Choice(
            name=choice_dict.get("name"),
            ctype=choice_dict.get("ctype", "uncontrollable"),
            domain=choice_dict.get("domain", []),
            probability=choice_dict.get("probability"),
        )
        return Episode.composite("choose", [_as_episode(ep) for ep in episodes], start=choice)

    def add_temporal_constraint(self, constraint):
        self.user_defined_temporal_constraints.add(constraint)
        return constraint

    def add_chance_constraint(self, constraint):
        self.user_defined_chance_constraints.add(constraint)
        return constraint

    def add_overall_temporal_constraint(self, ctype="controllable", lb=0.0,
                                        ub=float("inf")):
        if self.plan is None:
            start = Event(name="overall_start")
            end = Event(name="overall_end")
        else:
            start = self.plan.first_event
            end = self.plan.last_event
        tc = TemporalConstraint(start=start, end=end, ctype=ctype, lb=lb, ub=ub)
        self.add_temporal_constraint(tc)
        return tc

    def episode_by_id(self, episode_id):
        for ep in self._walk_episodes(self.plan):
            if getattr(ep, "id", None) == episode_id:
                return ep
        return None

    def to_ptpn(self, filename):
        with open(filename, "w") as stream:
            stream.write("# Minimal pTPN export generated by local RMPyL shim\n")
            stream.write("name: %s\n" % self.name)
            stream.write("events: %d\n" % len(self.events))
            stream.write("episodes:\n")
            for ep in self.primitive_episodes:
                stream.write("  - %s\n" % ep)
            stream.write("temporal_constraints:\n")
            for tc in self.temporal_constraints:
                stream.write("  - %s\n" % tc)

    def _walk_episodes(self, episode):
        if episode is None:
            return
        yield episode
        for child in getattr(episode, "internal_episodes", []):
            for subepisode in self._walk_episodes(child):
                yield subepisode


__all__ = [
    "ChanceConstraint",
    "Choice",
    "Episode",
    "Event",
    "RMPyL",
    "TemporalConstraint",
    "sequence_composition",
]
